BEGIN;

DROP TABLE IF EXISTS shipment_items CASCADE;
DROP TABLE IF EXISTS shipments CASCADE;
DROP TABLE IF EXISTS invoices CASCADE;
DROP TABLE IF EXISTS quality_checks CASCADE;
DROP TABLE IF EXISTS finished_goods_stock CASCADE;
DROP TABLE IF EXISTS production_batches CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS customer_orders CASCADE;
DROP TABLE IF EXISTS recipe_items CASCADE;
DROP TABLE IF EXISTS tech_cards CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS raw_material_stock CASCADE;
DROP TABLE IF EXISTS delivery_items CASCADE;
DROP TABLE IF EXISTS raw_material_deliveries CASCADE;
DROP TABLE IF EXISTS supplier_materials CASCADE;
DROP TABLE IF EXISTS raw_materials CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS role_permissions CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS suppliers CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS user_statuses CASCADE;
DROP TABLE IF EXISTS tech_card_statuses CASCADE;
DROP TABLE IF EXISTS quality_statuses CASCADE;
DROP TABLE IF EXISTS production_statuses CASCADE;
DROP TABLE IF EXISTS delivery_statuses CASCADE;
DROP TABLE IF EXISTS shipment_statuses CASCADE;
DROP TABLE IF EXISTS invoice_statuses CASCADE;
DROP TABLE IF EXISTS order_statuses CASCADE;

DROP FUNCTION IF EXISTS validate_delivery_item_expiry() CASCADE;
DROP FUNCTION IF EXISTS validate_shipment_dates() CASCADE;
DROP FUNCTION IF EXISTS audit_row_change() CASCADE;
DROP FUNCTION IF EXISTS log_auth_event(BIGINT, VARCHAR, INET, BOOLEAN) CASCADE;

DROP ROLE IF EXISTS bakery_client;
DROP ROLE IF EXISTS bakery_quality;
DROP ROLE IF EXISTS bakery_warehouse;
DROP ROLE IF EXISTS bakery_technologist;
DROP ROLE IF EXISTS bakery_admin;

COMMIT;
